# Generated by Django 5.2.1 on 2025-05-22 09:20

import django.core.validators
import file_api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='User-friendly name for the file', max_length=255)),
                ('file', models.FileField(help_text='The actual file to be stored', upload_to=file_api.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'json', 'csv', 'doc', 'docx'])])),
                ('file_type', models.CharField(help_text='File extension/type', max_length=10)),
                ('file_size', models.IntegerField(help_text='Size of file in bytes', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10485760)])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded')),
            ],
            options={
                'verbose_name': 'User File',
                'verbose_name_plural': 'User Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
