# Generated by Django 5.0.4 on 2025-05-17 17:09

import django.core.validators
import file_api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=file_api.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'json', 'csv', 'doc', 'docx'])])),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
