# Generated by Django 5.0.4 on 2025-05-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0002_userfile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='ownerId',
            field=models.CharField(default='hilloridesai@gmail.com', help_text='UserId of the user who uploaded the file', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfile',
            name='userIds',
            field=models.JSONField(blank=True, default=list, help_text='List of user ids with whom the file is shared', null=True),
        ),
    ]
